Feature/donation count and duration state
itk-dev/giv-din-stemme pull request #24
Opened 2024-08-26 10:29 UTC by jekuaitk

wip

2024-08-26 13:01 UTC, rimi-itk requested changes

2024-08-26 13:01 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/src/Helper/Helper.php
> +    }
```suggestion
    $totalDonationDuration = $this->getTotalDonationDuration();

    $this->state->set(self::GIV_DIN_STEMME_TOTAL_DONATION_DURATION_STATE_KEY, ($totalDonationDuration ?? 0) + $duration);
```

or

```suggestion
    $totalDonationDuration = $this->getTotalDonationDuration() ?? 0;
    $this->state->set(self::GIV_DIN_STEMME_TOTAL_DONATION_DURATION_STATE_KEY, $totalDonationDuration + $duration);
```

2024-08-26 13:48 UTC, jekuaitk commented on web/modules/custom/giv_din_stemme/src/Helper/Helper.php
> +  }
Changed reference link to https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Lock%21LockBackendInterface.php/group/lock/11.x, in which it explains acquire/wait.

2024-08-26 14:03 UTC, jekuaitk commented on web/themes/custom/giv_din_stemme_theme/texts/consent-text.html
Nope, but lets fix it here anyways.

2024-08-27 07:24 UTC, rimi-itk requested changes

2024-08-27 07:24 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/src/Helper/Helper.php
> +    $this->state->set(self::GIV_DIN_STEMME_DONATION_COUNT_STATE_KEY, ($currentTotal ?? 0) + 1);
Handle this like you handle the total above.

2024-08-27 07:24 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/src/Helper/Helper.php
> +    // @see https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Lock%21LockBackendInterface.php/group/lock/11.x
Thank you! 🎉

2024-08-27 10:53 UTC, rimi-itk approved these changes

2024-08-27 11:11 UTC, merged