Automatically stop recording after a minute
itk-dev/giv-din-stemme pull request #44
Opened 2024-08-28 12:01 UTC by jekuaitk

* Adds automatic recording stop after a minute

2024-08-28 13:58 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +          toggleButton.click();
Call `stopRecording` here since that's what you really want to do. Using code to click a button is rarely what you want.

2024-08-28 13:58 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +        setTimeout(durationChecker, 60 * 1000);
Consider adding a `const` with the timeout value.

2024-08-28 13:58 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +      durationChecker = () => {
`durationChecker` is not a good function name. Consider calling it `autoStopRecording` (which is only a little better, but much more “function name”-ish).

2024-08-28 13:58 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +          toggleButton.click();
It may be a good idea to tell the user that the recording has been stopped automatically. Our designer can design a message element that you can pass to `showElement`.

2024-08-28 17:00 UTC, jekuaitk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +          toggleButton.click();
Makes sense, fixed.

2024-08-28 17:17 UTC, jekuaitk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +      durationChecker = () => {
It is indeed bad naming. Renamed.

2024-08-28 17:18 UTC, jekuaitk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +          toggleButton.click();
Good idea.

2024-08-29 12:58 UTC, rimi-itk requested changes

2024-08-29 12:58 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +      autoStopRecording = () => {
Why don't you use `function autoStopRecording` to declare this function like you do with the other functions?

2024-08-29 12:58 UTC, rimi-itk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +          showElement(automaticallyStoppedRecordingMessageElement);
To make sure that more than one message is never shown, I suggest adding a `showMessage` function that hides all but one message:

```js
const showMessage(message) {
  hideElement(startRecordingMessageElement);
  hideElement(stopRecordingMessageElement);
  …
  showElement(message);
}
```

adding the message elements to an object (rather than having a variable for each) will make this much easier:

```js
const messages = {
  'start_recording': document.querySelector("#start_recording_message"),
}
```

2024-08-29 13:24 UTC, jekuaitk commented on web/modules/custom/giv_din_stemme/js/giv_din_stemme.js
> +          showElement(automaticallyStoppedRecordingMessageElement);
Fixed.

2024-08-29 13:45 UTC, rimi-itk approved these changes

2024-08-29 13:45 UTC, merged